backend:
  name: github
  repo: negolego/ElvidaStone
  branch: main
  base_url: https://elvidastone.pages.dev
  auth_endpoint: api/auth

# where files uploaded via the CMS are saced in your repo
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "gallery"
    label: "Photo Gallery"
    files:
      - label: "Gallery Photos"
        name: "photos"
        file: "data/gallery.json"
        fields:
          - label: "Photo List"
            name: "items"
            widget: "list"
            summary: "{{fields.title}} - {{fields.image}}"
            fields:
              - { label: "Title / Caption", name: "title", widget: "string"}
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Description (Optional)", name: "description", widget: "text", required: false }
