backend:
  name: github
  repo: negolego/ElvidaStone
  branch: main
  base_url: https://elvidastone.pages.dev
  auth_endpoint: api/auth

# where files uploaded via the CMS are saved in your repo
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "categories"
    label: "Categorii produse"
    folder: "data/categories"
    create: true
    format: "json"
    identifier_field: "category_name"
    fields:
      - {name: "category_name", label: "Numele categoriei", widget: "string"}
      - {name: "image", label: "Poza categoriei", widget: "image"}
      - name: "items"
        label: "Produse"
        widget: "list"
        summary: "{{fields.title}}"
        fields:
          - {name: "title", label: "Nume produs", widget: "string"}
          - name: "versions"
            label: "Variante"
            widget: "list"
            fields:
              - {name: "title", label: "Nume varianta", widget: "string"}
              - name: "images"
                label: "Poze"
                widget: "list"
                required: false
                field: {name: "image", label: "poza", widget: "image"}

